/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        brand: {
          50: 'var(--color-brand-50)',
          100: 'var(--color-brand-100)',
          200: 'var(--color-brand-200)',
          300: 'var(--color-brand-300)',
          400: 'var(--color-brand-400)',
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
          700: 'var(--color-brand-700)',
          800: 'var(--color-brand-800)',
          900: 'var(--color-brand-900)',
          950: 'var(--color-brand-950)',
        },
        neutral: {
          0: 'var(--color-neutral-0)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
          1000: 'var(--color-neutral-1000)',
        },
        red: {
          50: 'var(--color-red-50)',
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
          950: 'var(--color-red-950)',
        },
        yellow: {
          50: 'var(--color-yellow-50)',
          100: 'var(--color-yellow-100)',
          200: 'var(--color-yellow-200)',
          300: 'var(--color-yellow-300)',
          400: 'var(--color-yellow-400)',
          500: 'var(--color-yellow-500)',
          600: 'var(--color-yellow-600)',
          700: 'var(--color-yellow-700)',
          800: 'var(--color-yellow-800)',
          900: 'var(--color-yellow-900)',
          950: 'var(--color-yellow-950)',
        },
        emerald: {
          50: 'var(--color-emerald-50)',
          100: 'var(--color-emerald-100)',
          200: 'var(--color-emerald-200)',
          300: 'var(--color-emerald-300)',
          400: 'var(--color-emerald-400)',
          500: 'var(--color-emerald-500)',
          600: 'var(--color-emerald-600)',
          700: 'var(--color-emerald-700)',
          800: 'var(--color-emerald-800)',
          900: 'var(--color-emerald-900)',
          950: 'var(--color-emerald-950)',
        },
        cyan: {
          50: 'var(--color-cyan-50)',
          100: 'var(--color-cyan-100)',
          200: 'var(--color-cyan-200)',
          300: 'var(--color-cyan-300)',
          400: 'var(--color-cyan-400)',
          500: 'var(invisible--color-cyan-600)',
          700: 'var(--color-cyan-700)',
          800: 'var(--color-cyan-800)',
          900: 'var(--color-cyan-900)',
          950: 'var(--color-cyan-950)',
        },
        purple: {
          50: 'var(--color-purple-50)',
          100: 'var(--color-purple-100)',
          200: 'var(--color-purple-200)',
          300: 'var(--color-purple-300)',
          400: 'var(--color-purple-400)',
          500: 'var(--color-purple-500)',
          600: 'var(--color-purple-600)',
          700: 'var(--color-purple-700)',
          800: 'var(--color-purple-800)',
          900: 'var(--color-purple-900)',
          950: 'var(--color-purple-950)',
        },
        pink: {
          50: 'var(--color-pink-50)',
          100: 'var(--color-pink-100)',
          200: 'var(--color-pink-200)',
          300: 'var(--color-pink-300)',
          400: 'var(--color-pink-400)',
          500: 'var(invisible--color-pink-900)',
          950: 'var(--color-pink-950)',
        },
      },
      spacing: {
        0: 'var(--spacing-scale-0)',
        1: 'var(--spacing-scale-1)',
        2: 'var(--spacing-scale-2)',
        3: 'var(--spacing-scale-3)',
        4: 'var(--spacing-scale-4)',
        5: 'var(--spacing-scale-5)',
        6: 'var(--spacing-scale-6)',
        7: 'var(--spacing-scale-7)',
        8: 'var(--spacing-scale-8)',
        9: 'var(--spacing-scale-9)',
        10: 'var(--spacing-scale-10)',
        11: 'var(--spacing-scale-11)',
        12: 'var(--spacing-scale-12)',
        14: 'var(--spacing-scale-14)',
        16: 'var(--spacing-scale-16)',
        20: 'var(--spacing-scale-20)',
        24: 'var(--spacing-scale-24)',
        28: 'var(--spacing-scale-28)',
        32: 'var(--spacing-scale-32)',
        36: 'var(--spacing-scale-36)',
        40: 'var(--spacing-scale-40)',
        44: 'var(--spacing-scale-44)',
        48: 'var(--spacing-scale-48)',
        52: 'var(--spacing-scale-52)',
        56: 'var(--spacing-scale-56)',
        60: 'var(--spacing-scale-60)',
        64: 'var(--spacing-scale-64)',
        72: 'var(--spacing-scale-72)',
        80: 'var(--spacing-scale-80)',
        96: 'var(--spacing-scale-96)',
      },
      fontSize: {
        0: 'var(--spacing-size-0)',
        1: 'var(--spacing-size-1)',
        2: 'var(--spacing-size-2)',
        3: 'var(--spacing-size-3)',
        4: 'var(--spacing-size-4)',
        5: 'var(--spacing-size-5)',
        6: 'var(--spacing-size-6)',
        7: 'var(--spacing-size-7)',
        8: 'var(--spacing-size-8)',
        9: 'var(--spacing-size-9)',
        10: 'var(--spacing-size-10)',
        11: 'var(--spacing-size-11)',
        12: 'var(--spacing-size-12)',
        14: 'var(--spacing-size-14)',
        16: 'var(--spacing-size-16)',
        20: 'var(--spacing-size-20)',
        24: 'var(--spacing-size-24)',
        28: 'var(--spacing-size-28)',
        32: 'var(--spacing-size-32)',
        36: 'var(--spacing-size-36)',
        40: 'var(--spacing-size-40)',
        44: 'var(--spacing-size-44)',
        48: 'var(--spacing-size-48)',
        52: 'var(--spacing-size-52)',
        56: 'var(--spacing-size-56)',
        60: 'var(--spacing-size-60)',
        64: 'var(--spacing-size-64)',
        72: 'var(--spacing-size-72)',
        80: 'var(--spacing-size-80)',
        96: 'var(--spacing-size-96)',
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        sm: 'var(--border-radius-sm)',
        default: 'var(--border-radius-default)',
        lg: 'var(--border-radius-lg)',
        full: 'var(--border-radius-full)',
      },
      borderWidth: {
        0: 'var(--border-width-0)',
        1: 'var(--border-width-1)',
        2: 'var(--border-width-2)',
      },
      opacity: {
        visible: 'var(--opacity-visible)',
        hover: 'var(--opacity-hover)',
        disabled: 'var(--opacity-disabled)',
        loading: 'var(--opacity-loading)',
        invisible: 'var(--opacity-invisible)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontWeight: {
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
      },
      scale: {
        0: 'var(--spacing-scale-0)',
        1: 'var(--spacing-scale-1)',
        2: 'var(--spacing-scale-2)',
        3: 'var(--spacing-scale-3)',
        4: 'var(--spacing-scale-4)',
        5: 'var(--spacing-scale-5)',
        6: 'var(--spacing-scale-6)',
        7: 'var(--spacing-scale-7)',
        8: 'var(--spacing-scale-8)',
        9: 'var(--spacing-scale-9)',
        10: 'var(--spacing-scale-10)',
        11: 'var(--spacing-scale-11)',
        12: 'var(--spacing-scale-12)',
        14: 'var(--spacing-scale-14)',
        16: 'var(--spacing-scale-16)',
        20: 'var(--spacing-scale-20)',
        24: 'var(--spacing-scale-24)',
        28: 'var(--spacing-scale-28)',
        32: 'var(--spacing-scale-32)',
        36: 'var(--spacing-scale-36)',
        40: 'var(--spacing-scale-40)',
        44: 'var(--spacing-scale-44)',
        48: 'var(--spacing-scale-48)',
        52: 'var(--spacing-scale-52)',
        56: 'var(--spacing-scale-56)',
        60: 'var(--spacing-scale-60)',
        64: 'var(--spacing-scale-64)',
        72: 'var(--spacing-scale-72)',
        80: 'var(--spacing-scale-80)',
        96: 'var(--spacing-scale-96)',
      },
    },
  },
  plugins: [],
};
